language: mega
sudo: required
dist: trusty

cache:
  directories:
  - $HOME/.m2
  - src/main/angular/node_modules

before_script:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs

jobs:
  include: 
    - stage: commit stage
      script:
      - make build
      - wget -O codacy-coverage-reporter-assembly.jar https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/2.0.0/codacy-coverage-reporter-2.0.0-assembly.jar
      - java -cp codacy-coverage-reporter-assembly.jar com.codacy.CodacyCoverageReporter -l Java -r target/coverage-reports/jacoco.xml
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker tag menu-generation:latest $DOCKER_USERNAME/menu-generation:pending
      - docker push $DOCKER_USERNAME/menu-generation:pending
    - stage: acceptance testing
      script:
      - docker pull $DOCKER_USERNAME/menu-generation:pending
      - docker tag $DOCKER_USERNAME/menu-generation:pending menu-generation:latest
      - make test
    - stage: promote image
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker pull $DOCKER_USERNAME/menu-generation:pending
      - docker tag $DOCKER_USERNAME/menu-generation:pending $DOCKER_USERNAME/menu-generation:latest
      - docker tag $DOCKER_USERNAME/menu-generation:pending $DOCKER_USERNAME/menu-generation:$TRAVIS_BUILD_NUMBER
      - docker push $DOCKER_USERNAME/menu-generation:latest
      - docker push $DOCKER_USERNAME/menu-generation:$TRAVIS_BUILD_NUMBER

notifications:
  email:
    on_success: change
    on_failure: always