spring:
  profiles:
    active:
    - in-memory

management:
  context-path: /api/management

security:
  user:
    name: management
    password: management
    role:
    - ACTUATOR

cena:
  menu-generation:
    authentication:
      ingredient-manager:
        username: ingredient-manager
        password: ingredient-manager
      users:
        - username: authenticated-user
          password: authenticated-user
        - username: another-user
          password: another-user

### Logging configuration
logging:
  pattern:
    console: '[%-5p] %d | %c{1}:%L | %m%n'
  level:
    org.adhuc.cena.menu: TRACE
    org.springframework.security: ERROR
    org.springframework.boot.autoconfigure: ERROR
