spring:
  profiles:
    active:
    - in-memory
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
    cache-period: 3600

management:
  context-path: /api/management

security:
  ignored:
  - /static/**
  - /assets/**
  - '*.chunk.js'
  user:
    name: management
    password: management
    role:
    - ACTUATOR

cena:
  menu-generation:
    authentication:
      ingredient-manager:
        username: ingredient-manager
        password: ingredient-manager
      users:
      - username: authenticated-user
        password: authenticated-user
      - username: another-user
        password: another-user
    secured-resources:
    - method: get
      paths:
      - '/api/menus/**'
    - method: post
      paths:
      - '/api/ingredients/**'
      - '/api/recipes/**'
      - '/api/menus/**'
    - method: put
      paths:
      - '/api/ingredients/**'
      - '/api/recipes/**'

### Logging configuration
logging:
  pattern:
    console: '[%-5p] %d | %c{1}:%L | %m%n'
  level:
    org.adhuc.cena.menu: TRACE
    org.springframework.security: ERROR
    org.springframework.boot.autoconfigure: ERROR
