spring:
  profiles:
    active:
    - in-memory

management:
  context-path: /management

security:
  user:
    name: management
    password: management
    role:
    - ACTUATOR
  ignored:
  - /api/**
  - /docs/**

### Logging configuration
logging:
  pattern:
    console: '[%-5p] %d | %c{1}:%L | %m%n'
  level:
    org.adhuc.cena.menu: TRACE
